# Generated by Django 4.1.3 on 2022-11-30 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0009_alter_timeslot_patient'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('day', 'start', 'end')},
        ),
    ]
