# Generated by Django 4.1.3 on 2022-12-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0013_alter_timeslot_end_alter_timeslot_start'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('day', 'start', 'end'), name='One timeslot with same start and end value per day'),
        ),
    ]
