# Generated by Django 4.1.3 on 2022-12-01 09:26

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0014_alter_timeslot_unique_together_alter_day_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeslot',
            name='One timeslot with same start and end value per day',
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('day', 'start', 'end'), name='One timeslot with same start and end value per day'),
        ),
    ]
