# Generated by Django 4.1.4 on 2022-12-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0019_timeslot_one timeslot with same start and end value per day'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='betaald',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='eerste_afspraak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='extra_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
