# Generated by Django 4.1.3 on 2022-11-30 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0002_timeslot_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='available',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='appointment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='amb_app.appointment', verbose_name='Appointment'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timeslots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amb_app.timeslot', verbose_name='Timeslots')),
            ],
        ),
    ]
