# Generated by Django 4.1.3 on 2022-11-30 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0003_remove_appointment_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='timeslots',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='day',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='amb_app.day', verbose_name='Day'),
            preserve_default=False,
        ),
    ]
