# Generated by Django 4.1.3 on 2022-11-30 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0006_remove_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amb_app.day', verbose_name='Day'),
        ),
    ]
