# Generated by Django 4.1.3 on 2022-12-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0012_alter_timeslot_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
