# Generated by Django 4.1.3 on 2022-12-01 09:28

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0015_remove_timeslot_one timeslot with same start and end value per day_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeslot',
            name='One timeslot with same start and end value per day',
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('day', 'start', 'end'), name='One timeslot with same start and end value per day'),
        ),
    ]
