# Generated by Django 4.1.3 on 2022-12-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0016_remove_timeslot_one timeslot with same start and end value per day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['day', 'start', 'end']},
        ),
        migrations.RemoveConstraint(
            model_name='timeslot',
            name='One timeslot with same start and end value per day',
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('day', 'start', 'end'), name='One timeslot with same start and end value per day'),
        ),
    ]
