# Generated by Django 4.1.3 on 2022-12-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amb_app', '0018_remove_timeslot_one timeslot with same start and end value per day'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('day', 'start', 'end'), name='One timeslot with same start and end value per day'),
        ),
    ]
